version: "3.9"
services:
  nginx:
    image: alexroot/alpine:v0.1.1
    container_name: nginx
    working_dir: /data
    volumes:
      - ./data/data1/default2.conf:/etc/nginx/http.d/default.conf
      - ./data/data1/index.html:/var/www/html/index.html     
    command: sh -c "nginx && curl localhost:8080"
    ports: 
      - 8080:8081




      
