# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = true

    
	
  config.vm.define "router1" do |router1|
    router1.vm.hostname = 'router1'
    router1.vm.network "private_network", ip: "172.20.10.1", netmask: "255.255.255.0" , adapter: 2,  virtualbox__intnet: "router1"
    router1.vm.network "private_network", ip: "192.168.0.1", netmask: "255.255.255.252" , adapter: 3,  virtualbox__intnet: "router12"
    router1.vm.network "private_network", ip: "192.168.200.1", netmask: "255.255.255.252" , adapter: 4,  virtualbox__intnet: "router13"
    router1.vm.provider :virtualbox do |v|
		v.name = "router1"
    end

    router1.vm.provision "ansible" do |ansible|
        ansible.playbook = "router1.yml"
	end
	
  end
  
  config.vm.define "router2", primary: true do |router2|
    router2.vm.hostname = 'router2'
    router2.vm.network "private_network", ip: "172.20.20.1", netmask: "255.255.255.0" , adapter: 2,  virtualbox__intnet: "router2"
    router2.vm.network "private_network", ip: "192.168.0.2", netmask: "255.255.255.252" , adapter: 3,  virtualbox__intnet: "router12"
    router2.vm.network "private_network", ip: "192.168.100.2", netmask: "255.255.255.252" , adapter: 4,  virtualbox__intnet: "router23"
    router2.vm.provider :virtualbox do |v|
		v.name = "router2"

    end

    router2.vm.provision "ansible" do |ansible|
        ansible.playbook = "router2.yml"
	end
	
  end

  config.vm.define "router3" do |router3|
    router3.vm.hostname = 'router3'
    router3.vm.network "private_network", ip: "172.20.30.1", netmask: "255.255.255.0" , adapter: 2,  virtualbox__intnet: "router3"
    router3.vm.network "private_network", ip: "192.168.200.2", netmask: "255.255.255.252" , adapter: 3,  virtualbox__intnet: "router13"
    router3.vm.network "private_network", ip: "192.168.100.1", netmask: "255.255.255.252" , adapter: 4,  virtualbox__intnet: "router23"
    router3.vm.provider :virtualbox do |v|
		v.name = "router3"
    end

    router3.vm.provision "ansible" do |ansible|
        ansible.playbook = "router3.yml"
	end
	
  end
  
end