---
 - name: Set hostname
   hostname: 
     name: ipaserver.otus.lan

 - name: install epel-release
   yum: 
     name: epel-release 
     state: latest 

 - name: ipa-server initial
   shell: "dnf module enable idm:DL1"
 - name: ipa-server initial
   shell: "dnf distro-sync"

 - name: install ipa-server
   yum: 
     name: {{ item }} 
     state: latest 
   with_items:
    - ipa-server
    - ipa-server-dns
    - nss

 - name: create /etc/hosts from template
   template:
     src: hosts.j2
     dest: /etc/hosts

 - name: dbus service restart
   systemd:
     name: dbus.service
     state: restarted
     enabled: yes

 - name: ipa-server initial
   ignore_errors: True
   register: result
   shell: ipa-server-install --setup-dns --auto-reverse --mkhomedir --hostname={{ server }} --domain={{ domain }} --realm={{ realm }} --ds-password={{ dbpassword }} --admin-password={{ password }} --no-forwarders -U

 - name: IPA-Server reinstall
   when: result is failed
   shell: systemctl restart dbus.service && ipa-server-install --uninstall -U && ipa-server-install -U --setup-dns --auto-reverse --mkhomedir --hostname={{ server }} --domain={{ domain }} --realm={{ realm }} --ds-password={{ dbpassword }} --admin-password={{ password }} --no-forwarders -U
 - name: ipa-server initial
   shell: "firewall-cmd --add-service={http,https,dns,ntp,freeipa-ldap,freeipa-ldaps} --permanent && firewall-cmd --reload"