# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/8"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end
  
  config.vm.define "inetRouter" do |inetRouter|
    inetRouter.vm.hostname = "inetRouter"
    inetRouter.vm.network "private_network", adapter: 2, 
    virtualbox__intnet: "inetRouter"
    inetRouter.vm.network "private_network", adapter: 3, 
    virtualbox__intnet: "inetRouter"

    inetRouter.vm.provider :virtualbox do |vb|
      vb.name = "inetRouter"
      vb.memory = 4096
      vb.cpus = 2
    end
  end

  config.vm.define "centralRouter" do |centralRouter|
    centralRouter.vm.hostname = "centralRouter"
    centralRouter.vm.network "private_network", adapter: 2,
    virtualbox__intnet: "inetRouter"
    centralRouter.vm.network "private_network", adapter: 3,
    virtualbox__intnet: "inetRouter"
    centralRouter.vm.network "private_network", adapter: 4,
    virtualbox__intnet: "router-subnet"
    centralRouter.vm.network "private_network",adapter: 5,
    virtualbox__intnet:"router-subnet"
    centralRouter.vm.provider :virtualbox do |vb|
      vb.name = "centralRouter"
      vb.memory = 4096
      vb.cpus = 2
    end
  end
  config.vm.define "testRouter1" do |testRouter1|
    testRouter1.vm.hostname = "testRouter1"
    testRouter1.vm.network "private_network", adapter: 2,
    virtualbox__intnet: "router-subnet"
    testRouter1.vm.network "private_network", adapter: 3,
    virtualbox__intnet: "test-subnet-vlan100"
    testRouter1.vm.provider :virtualbox do |vb|
      vb.name = "testRouter1"
      vb.memory = 512
      vb.cpus = 1
    end
  end
  config.vm.define "testRouter2" do |testRouter2|
    testRouter2.vm.hostname = "testRouter2"
    testRouter2.vm.network "private_network", adapter: 2,
    virtualbox__intnet: "router-subnet"
    testRouter2.vm.network "private_network", adapter: 3,
    virtualbox__intnet: "test-subnet-vlan200"
    testRouter2.vm.provider :virtualbox do |vb|
      vb.name = "testRouter2"
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "testClient1" do |testClient1|
    testClient1.vm.hostname = "testClient1"
    testClient1.vm.network "private_network", adapter: 2,
    virtualbox__intnet: "test-subnet-vlan100"
    testClient1.vm.provider :virtualbox do |vb|
      vb.name = "testClient1"
      vb.memory = 512
      vb.cpus = 1
    end
  end
  config.vm.define "testClient2" do |testClient2|
    testClient2.vm.hostname = "testClient2"
    testClient2.vm.network "private_network", adapter: 2,
    virtualbox__intnet: "test-subnet-vlan100"
    testClient2.vm.provider :virtualbox do |vb|
      vb.name = "testClient2"
      vb.memory = 512
      vb.cpus = 1
    end
  end
  config.vm.define "testServer1" do |testServer1|
    testServer1.vm.hostname = "testServer1"
    testServer1.vm.network "private_network", adapter: 2,
    virtualbox__intnet: "test-subnet-vlan100"
    testServer1.vm.provider :virtualbox do |vb|
      vb.name = "testServer1"
      vb.memory = 512
      vb.cpus = 1
    end
end
config.vm.define "testServer2" do |testServer2|
  testServer2.vm.hostname = "testServer2"
  testServer2.vm.network "private_network", adapter: 2,
  virtualbox__intnet: "test-subnet-vlan100"
  testServer2.vm.provider :virtualbox do |vb|
    vb.name = "testServer2"
    vb.memory = 512
    vb.cpus = 1
  end
end
end
