# -*- mode:ruby -*-
#vi: set ft=ruby :
Vagrant.configure(2) do |config|
    config.vm.box = "debian/buster64"
    config.vm.box_version = "10.20210409.1"
    config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "pam" do |pam|
    pam.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    pam.vm.hostname = "nginx"
    pam.vm.provision "shell", path: "pam.sh"
  end


end 