# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :lvm => {
        :box_name => "centos/7",
        :box_version => "1905.1",
        :ip_addr => '192.168.11.111',
    :disks => {
        :sata1 => {
            :dfile =>home+'/VirtualBox VMs/sata31.vdi',
            :size => 10240,
            :port => 1
        },
        :sata2 => {
            :dfile =>home+'/VirtualBox VMs/sata32.vdi',
            :size => 2048, # Megabytes
            :port => 2
        },
        :sata3 => {
            :dfile =>home+'/VirtualBox VMs/sata33.vdi',
            :size => 1024, # Megabytes
            :port => 3
        },
        :sata4 => {
            :dfile =>home+'/VirtualBox VMs/sata34.vdi',
            :size => 1024,
            :port => 4
        },
        :sata5 => {
            :dfile =>home+'/VirtualBox VMs/sata35.vdi',
            :size => 1024,
            :port => 5
        }
    }
  },
}

Vagrant.configure("2") do |config|

    config.vm.box_version = "1905.1"
    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
                    needsController = false
            boxconfig[:disks].each do |dname, dconf|
                unless File.exist?(dconf[:dfile])
                  vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                  needsController =  true
                            end
  
            end
                    if needsController == true
                       vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                       boxconfig[:disks].each do |dname, dconf|
                           vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                       end
                    end
            end
  
        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            yum install -y mdadm smartmontools hdparm gdisk xfsdump ;
            pvcreate /dev/sdb ; pvcreate /dev/sd[d,e];pvcreate /dev/sdc;
            vgcreate root /dev/sdb ; vgcreate home /dev/sdc; vgcreate var /dev/sd[d,e];
            lvcreate -l 80%FREE -n root root;mkfs.xfs /dev/root/root; 
            lvcreate -l 100%FREE -n var var;mkfs.btrfs /dev/var/var;
            lvcreate -l 100%FREE -n home home; mkfs.xfs /dev/home/home;
            xfsdump -J - /dev/VolGroup00/LogVol00 | xfsrestore -J - /mnt #&&
           for i in /proc/ /sys/ /dev/ /run/ /boot/ ; do mount --bind $i /mnt$i; done ;
         chroot /mnt/ ;  grub2-mkconfig -o /boot/grub2/grub.cfg ;
           cd /boot ; for i in `ls initramfs-*img` ;
         do dracut -v $i `echo $i|sed "s/initramfs-//g;s/.img//g"` --force; done ; 
            #echo "This is a test 2 again" | sed 's/rd.lvm.lv=VolGroup00\/\LogVol00\/\rd.lvm.lv=root\/\root/g' /boot/grub2/grub.cfg ;
            #sed 's/root=\/\dev\/\mapper\/\VolGroup00-LogVol00/root=\/\dev\/\mapper\/\root-root/g' /boot/grub2/grub.cfg;
          SHELL
  
        end
    end
  end
  
